[package]
name = "kuqu"
version = "0.1.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2024"
description = "SQL for Kubernetes resources"
repository = "https://github.com/ynqa/kuqu"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.89"
clap = { version = "4.5.47", features = ["derive"] }
kubex = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.47.1", features = ["full"] }

# datafusion ecosystem
datafusion = "50.0.0"
datafusion-datasource = "50.0.0"
datafusion-datasource-json = "50.0.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
